Ports:
  zone-0-0:
    http: 8610
    ws: 8611
  zone-0-1:
    http: 8542
    ws: 8643
  zone-0-2:
    http: 8674
    ws: 8675
  zone-1-0:
    http: 8512
    ws: 8613
  zone-1-1:
    http: 8544
    ws: 8645
  zone-1-2:
    http: 8576
    ws: 8677
  zone-2-0:
    http: 8614
    ws: 8615
  zone-2-1:
    http: 8646
    ws: 8647
  zone-2-2:
    http: 8678
    ws: 8679
EtxFreq: 0